apache/doris-manager

.asf.yaml
1. move GitBox mail to commits@doris
2. Fix typo of .asf.yml
=> [community] move GitBox mail to commits@doris

manager/conf/manager.conf, manager/dm-agent/src/main/java/org/apache/doris/manager/agent/util/Request.java, manager/dm-server/src/main/java/org/apache/doris/stack/util/TelnetUtil.java, manager/doc/Doris Manager Server 接口文档.md, manager/doris-manager/config/webpack.dev.config.js, manager/general/src/main/java/org/apache/doris/stack/exception/DorisHttpPortErrorException.java, manager/general/src/main/java/org/apache/doris/stack/exception/DorisIpErrorException.java, manager/general/src/main/java/org/apache/doris/stack/exception/DorisJdbcPortErrorException.java, manager/general/src/main/java/org/apache/doris/stack/exception/DorisUerOrPassErrorException.java, manager/general/src/main/java/org/apache/doris/stack/exception/DorisUserNoPermissionException.java, manager/general/src/test/java/org/apache/doris/stack/service/user/AuthenticationServiceTest.java, manager/general/src/test/java/org/apache/doris/stack/service/user/UserServiceTest.java, manager/manager-server/src/main/java/org/apache/doris/stack/ManagerSwaggerConfig.java, manager/manager-server/src/test/java/org/apache/doris/stack/service/PaloUserSpaceServiceTest.java
=> fix baidu mail bug

manager/dm-agent/pom.xml
pack resource includes file into jar
=> add dm-agent resource includes

frontend/src/components/sidebar/sidebar.tsx, frontend/src/routes/cluster/cluster.utils.ts, frontend/src/routes/cluster/configuration/check-modal.tsx, frontend/src/routes/cluster/configuration/edit-modal.tsx, frontend/src/routes/space/access-cluster/access-cluster.tsx, frontend/src/routes/space/access-cluster/steps/cluster-verify/cluster-verify.tsx, frontend/src/routes/space/access-cluster/steps/connect-cluster/connect-cluster.tsx, frontend/src/routes/space/components/node-verify/node-verify.tsx, frontend/src/routes/space/new-cluster/new-cluster.tsx, frontend/src/routes/space/new-cluster/steps/add-node/add-node.tsx, frontend/src/routes/space/new-cluster/steps/add-node/node-list/node-list.tsx, frontend/src/routes/space/new-cluster/steps/cluster-deploy/cluster-deploy.tsx, frontend/src/routes/space/new-cluster/steps/cluster-plan/cluster-plan.tsx, frontend/src/routes/space/new-cluster/steps/install-options/install-options.tsx, frontend/src/routes/space/space.utils.ts
1. Add validation for next step when setting up a new cluster or access to an existing cluster.
2. Optimize the style of user setting page.
3. Remove ODBC URL in cluster overview.
4. Add effective range for param configuration.
6. Has unit tests been added: (Yes/No/No Need)
7. Has document been added or modified: (Yes/No/No Need)
8. Does it need to update dependencies: (Yes/No)
9. Are there any changes that cannot be rolled back: (Yes/No)
=> [fix] fix manager1.0.0 frontend bugs

build.sh
=> Optimize compilation scripts

manager/manager/src/main/java/org/apache/doris/stack/connector/PaloQueryClient.java, manager/manager/src/main/java/org/apache/doris/stack/model/response/construct/NativeQueryResp.java
Replace doris http query client with jdbc due to open source protocol issues.
1. Does it affect the original behavior: No
2. Has unit tests been added: (No
=> replace doris http query client with jdbc

manager/dm-common/src/main/java/org/apache/doris/manager/common/heartbeat/config/AgentInstallEventConfigInfo.java, manager/dm-server/src/main/java/org/apache/doris/stack/control/manager/DorisClusterManager.java, manager/dm-server/src/main/java/org/apache/doris/stack/control/manager/ResourceClusterManager.java, manager/dm-server/src/main/java/org/apache/doris/stack/control/manager/ResourceNodeAndAgentManager.java, manager/dm-server/src/main/java/org/apache/doris/stack/control/request/handler/DorisClusterCreationRequestHandler.java, manager/dm-server/src/main/java/org/apache/doris/stack/control/request/handler/DorisClusterTakeOverRequestHandler.java, manager/dm-server/src/main/java/org/apache/doris/stack/model/request/control/DorisClusterCreationReq.java, manager/dm-server/src/main/java/org/apache/doris/stack/model/request/control/DorisClusterTakeOverReq.java, manager/dm-server/src/main/java/org/apache/doris/stack/shell/BaseCommand.java, manager/manager-bin/agent/bin/agent_start.sh
Now, user can custom agent port setting.
3. Has document been added or modified: Yes
=> [feature] support to set agent port by user

frontend/public/index.html
=> [improvement](frontend)update document title

frontend/public/index.html, frontend/src/routes/admin/people/role/list/list.tsx, frontend/src/routes/admin/people/role/member/member.tsx
=> [fix](frontend)fix bug with role list navigate to role detail page failure

frontend/src/components/auths/require-initialized.tsx, frontend/src/components/sidebar/sidebar.tsx, frontend/src/hooks/use-auth.ts, frontend/src/index.css, frontend/src/routes/initialize/initialize-set-type.tsx
fix require-initialized route navigate error
```<RequireInitialized navigator="initialize" />``` makes initialize router error, it should be ```/initialize```
1. Does it affect the original behavior: No
3. Has document been added or modified: No
=> [fix] fix require-initialized route navigate error

frontend/src/routes/space/components/node-verify/node-verify.tsx
1. Fix the condition for polling in node verify page.
=> [Fix] Fix the condition for polling in node verify page.

manager/dm-common/src/main/java/org/apache/doris/manager/common/heartbeat/config/AgentUnInstallEventConfigInfo.java, manager/dm-common/src/main/java/org/apache/doris/manager/common/heartbeat/stage/AgentUnInstallEventStage.java, manager/dm-server/src/main/java/org/apache/doris/stack/component/DorisManagerUserSpaceComponent.java, manager/dm-server/src/main/java/org/apache/doris/stack/control/manager/DorisClusterManager.java, manager/dm-server/src/main/java/org/apache/doris/stack/control/manager/ResourceClusterManager.java, manager/dm-server/src/main/java/org/apache/doris/stack/control/manager/ResourceNodeAndAgentManager.java, manager/dm-server/src/main/java/org/apache/doris/stack/shell/BaseCommand.java, manager/dm-server/src/main/java/org/apache/doris/stack/shell/SSH.java, manager/dm-server/src/main/java/org/apache/doris/stack/util/Constants.java, manager/manager-server/src/main/java/org/apache/doris/stack/service/PaloUserSpaceService.java, manager/resource-common/src/main/java/org/apache/doris/stack/dao/ClusterInstanceRepository.java, manager/resource-common/src/main/java/org/apache/doris/stack/dao/ClusterModuleServiceRepository.java
remove blocking ssh interactive mode，and support to start and stop node agents async.
=> [improvement] node agent async start and stop

frontend/src/common/common.data.ts, frontend/src/hooks/use-auth.ts, frontend/src/routes/cluster/components/liquid-fill-chart/index.tsx, frontend/src/routes/cluster/overview/index.tsx, frontend/src/routes/initialize/auths/auth.tsx, frontend/src/routes/initialize/auths/components/admin-user/admin-user.tsx, frontend/src/routes/initialize/initialize-set-type.tsx, frontend/src/routes/initialize/initialize.tsx, frontend/src/routes/passport/login.tsx
1. Fix the disk occupancy display error
2. Fix initialize error
3. Has unit tests been added: (Yes/No/No Need)
4. Has document been added or modified: (Yes/No/No Need)
5. Does it need to update dependencies: (Yes/No)
6. Are there any changes that cannot be rolled back: (Yes/No)
=> [Fix] Fix the disk occupancy display error and initialize error

manager/dm-server/src/main/java/org/apache/doris/stack/component/DorisManagerUserSpaceComponent.java, manager/dm-server/src/main/java/org/apache/doris/stack/control/request/handler/DorisClusterTakeOverRequestHandler.java, manager/general/src/main/java/org/apache/doris/stack/util/CredsUtil.java, manager/manager/src/main/java/org/apache/doris/stack/connector/DorisNodesClient.java, manager/manager/src/main/java/org/apache/doris/stack/connector/PaloFileUploadClient.java, manager/manager/src/main/java/org/apache/doris/stack/connector/PaloForwardManagerClient.java, manager/manager/src/main/java/org/apache/doris/stack/connector/PaloLoginClient.java, manager/manager/src/main/java/org/apache/doris/stack/connector/PaloMetaInfoClient.java, manager/manager/src/main/java/org/apache/doris/stack/connector/PaloQueryClient.java, manager/manager/src/main/java/org/apache/doris/stack/connector/PaloStatisticClient.java, manager/resource-common/src/main/java/org/apache/doris/stack/entity/ClusterInfoEntity.java
encrypt doris password when creating doris user
2. Has unit tests been added: /No
=> [fix] encrypt doris password

manager/conf/manager.conf, manager/general/src/main/java/org/apache/doris/stack/constant/EnvironmentDefine.java, manager/general/src/main/java/org/apache/doris/stack/exception/ConfigItemException.java, manager/general/src/main/java/org/apache/doris/stack/util/CommonPropertyUtil.java, manager/general/src/main/java/org/apache/doris/stack/util/CredsUtil.java, manager/manager-server/src/main/java/org/apache/doris/stack/DorisManager.java
we remove the default encrypt key, users have to config encrypt key in conf file.
=> [fix] remove the default encrypt key

build.sh
If some error happen, the build process should be stopped.
=> [fix] add set -e for build.sh

.github/workflows/build-extension.yml
=> [chore] fix workflow

manager/dm-agent/pom.xml, manager/dm-server/pom.xml, manager/dm-server/src/main/java/org/apache/doris/stack/control/manager/ResourceClusterManager.java, manager/pom.xml
https://github.com/apache/incubator-doris-manager/pull/48
=> [fix] merge #48

manager/dm-agent/pom.xml, manager/dm-server/pom.xml, manager/dm-server/src/main/java/org/apache/doris/stack/control/manager/ResourceClusterManager.java, manager/pom.xml
Reverts apache/incubator-doris-manager#49
=> Revert "[fix] merge #48"

manager/dm-agent/src/main/java/org/apache/doris/manager/agent/exceptions/InstanceNotInstallException.java, manager/dm-agent/src/main/java/org/apache/doris/manager/agent/exceptions/InstanceNotRunningException.java, manager/dm-agent/src/main/java/org/apache/doris/manager/agent/exceptions/InstanceServiceException.java, manager/dm-agent/src/main/java/org/apache/doris/manager/agent/service/HeartBeatService.java, manager/dm-agent/src/main/java/org/apache/doris/manager/agent/service/heartbeat/DorisInstanceOperator.java, manager/dm-agent/src/main/java/org/apache/doris/manager/agent/service/heartbeat/InstanceEventHandler.java, manager/dm-agent/src/main/java/org/apache/doris/manager/agent/util/Request.java, manager/dm-agent/src/main/resources/application.properties, manager/dm-common/pom.xml, manager/dm-common/src/main/java/org/apache/doris/manager/common/heartbeat/HeartBeatContext.java, manager/dm-common/src/main/java/org/apache/doris/manager/common/heartbeat/HeartBeatResult.java, manager/dm-common/src/main/java/org/apache/doris/manager/common/heartbeat/InstanceInfo.java, manager/dm-common/src/main/java/org/apache/doris/manager/common/heartbeat/InstanceStateResult.java, manager/dm-common/src/main/java/org/apache/doris/manager/common/util/ConfigDefault.java, manager/dm-common/src/main/java/org/apache/doris/manager/common/util/ServerAndAgentConstant.java, manager/dm-server/src/main/java/org/apache/doris/stack/control/manager/DorisClusterModuleManager.java, manager/dm-server/src/main/java/org/apache/doris/stack/control/manager/ResourceClusterManager.java, manager/dm-server/src/main/java/org/apache/doris/stack/control/manager/ResourceNodeAndAgentManager.java, manager/dm-server/src/main/java/org/apache/doris/stack/controller/control/ResourceClusterNodeController.java, manager/dm-server/src/main/java/org/apache/doris/stack/service/control/ResourceClusterNodeService.java
Agent report instance state to Server
1. Does it affect the original behavior: No
3. Has document been added or modified: Yes
=> [feature] instance state report

frontend/src/routes/tree/index.tsx
=> [improve](frontend)Set the data page displays information for the first tree node by default

manager/manager-bin/agent/bin/download_doris.sh, manager/resource-common/src/main/java/org/apache/doris/stack/dao/ResourceNodeRepository.java
2. Has unit tests been added: No Need
=> [fix] optimize the decompression script to adapt different doris package name

manager/manager-bin/stop_manager.sh
fix the way to find the process number
=> [Fix] fix the way to find the process number

.asf.yaml, README.md
=> [TLP] remove incubator

docs/Doris Manger Initializing.md
=> Update Doris Manger Initializing.md
